### ISSUE TITLE
Error if component uses IxSelect or IxDropdown in unit test

### ISSUE THREAD

**Issue by adam-elias** [siemens/ix#1065]
### Prerequisites

- [X] I have not leaked any internal company information.
- [X] I have not posted internal links or code snippets.

### What happened?

Similarly the already fixed #882, this error only occurs in unit test, and not breaking that, just a log message, and i only observed if the problematic component has multiple unit test. If you have at least 4, than it is observable easily. I observed this bug with both the IxSelect component and the IxDropdown as well. My reasoning why this is an issue is also the same as the previous fixed issue.

```
ERROR: TypeError: Cannot read properties of undefined (reading 'destroy')
TypeError: Cannot read properties of undefined (reading 'destroy')
    at Dropdown.proto.disconnectedCallback (https://ne22ajecdpar-nf1l--9876--26ebe8bf.local-credentialless.webcontainer.io/_karma_webpack_/node_modules_siemens_ix_dist_esm_ix-select_entry_js.js:509:35)
    at safeCall (https://ne22ajecdpar-nf1l--9876--26ebe8bf.local-credentialless.webcontainer.io/_karma_webpack_/vendor.js:2845:30)
    at disconnectedCallback (https://ne22ajecdpar-nf1l--9876--26ebe8bf.local-credentialless.webcontainer.io/_karma_webpack_/vendor.js:3151:7)
    at https://ne22ajecdpar-nf1l--9876--26ebe8bf.local-credentialless.webcontainer.io/_karma_webpack_/vendor.js:3358:25
    at Object.jmp (https://ne22ajecdpar-nf1l--9876--26ebe8bf.local-credentialless.webcontainer.io/_karma_webpack_/vendor.js:3674:13)
    at HostElement.disconnectedCallback (https://ne22ajecdpar-nf1l--9876--26ebe8bf.local-credentialless.webcontainer.io/_karma_webpack_/vendor.js:3358:15)
    at _ZoneDelegate.invoke (https://ne22ajecdpar-nf1l--9876--26ebe8bf.local-credentialless.webcontainer.io/_karma_webpack_/polyfills.js:348:158)
    at ProxyZoneSpec.onInvoke (https://ne22ajecdpar-nf1l--9876--26ebe8bf.local-credentialless.webcontainer.io/_karma_webpack_/vendor.js:7644:33)
    at _ZoneDelegate.invoke (https://ne22ajecdpar-nf1l--9876--26ebe8bf.local-credentialless.webcontainer.io/_karma_webpack_/polyfills.js:348:46)
```

```
ERROR: TypeError: Cannot read properties of undefined (reading 'destroy')
TypeError: Cannot read properties of undefined (reading 'destroy')
    at Select.proto.disconnectedCallback (https://ne22ajecdpar-nf1l--9876--26ebe8bf.local-credentialless.webcontainer.io/_karma_webpack_/node_modules_siemens_ix_dist_esm_ix-select_entry_js.js:509:35)
    at safeCall (https://ne22ajecdpar-nf1l--9876--26ebe8bf.local-credentialless.webcontainer.io/_karma_webpack_/vendor.js:2845:30)
    at disconnectedCallback (https://ne22ajecdpar-nf1l--9876--26ebe8bf.local-credentialless.webcontainer.io/_karma_webpack_/vendor.js:3151:7)
    at https://ne22ajecdpar-nf1l--9876--26ebe8bf.local-credentialless.webcontainer.io/_karma_webpack_/vendor.js:3358:25
    at Object.jmp (https://ne22ajecdpar-nf1l--9876--26ebe8bf.local-credentialless.webcontainer.io/_karma_webpack_/vendor.js:3674:13)
    at HostElement.disconnectedCallback (https://ne22ajecdpar-nf1l--9876--26ebe8bf.local-credentialless.webcontainer.io/_karma_webpack_/vendor.js:3358:15)
    at _ZoneDelegate.invoke (https://ne22ajecdpar-nf1l--9876--26ebe8bf.local-credentialless.webcontainer.io/_karma_webpack_/polyfills.js:348:158)
    at ProxyZoneSpec.onInvoke (https://ne22ajecdpar-nf1l--9876--26ebe8bf.local-credentialless.webcontainer.io/_karma_webpack_/vendor.js:7644:33)
    at _ZoneDelegate.invoke (https://ne22ajecdpar-nf1l--9876--26ebe8bf.local-credentialless.webcontainer.io/_karma_webpack_/polyfills.js:348:46)
```

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

2.0.4

### Code to produce this issue.

```shell
https://stackblitz.com/edit/ne22aj-ecdpar
```

**Comment by matthiashader** [comment]
Internal ref [IX-877]

**Comment by jul-lam** [comment]
Please upgrade to version 2.1.0 or later, as the issue has been resolved.

**Comment by adam-elias** [comment]
Thank you!
