### ISSUE TITLE
jest test fails with modal: HTMLDialogElement not existing / Error: Uncaught [TypeError: this.dialog.close is not a function]

### ISSUE THREAD

**Issue by james-williams-siemens** [siemens/ix#1109]
### Prerequisites

- [X] I have not leaked any internal company information.
- [X] I have not posted internal links or code snippets.

### What happened?

When trying to write a jest test that requires interacting with a modal I get error when trying to close it:

```
  console.error
    HTMLDialogElement not existing

      at Modal.showModal (node_modules/@siemens/ix/components/src/components/modal/modal.tsx:171:15)

  console.error
    Error: Uncaught [TypeError: this.dialog.close is not a function]
        at reportException (/workspace/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
        at runAnimationFrameCallbacks (/workspace/node_modules/jsdom/lib/jsdom/browser/Window.js:601:13)
        at Timeout.<anonymous> (/workspace/node_modules/jsdom/lib/jsdom/browser/Window.js:577:11)
        at listOnTimeout (node:internal/timers:573:17)
        at processTimers (node:internal/timers:514:7) TypeError: this.dialog.close is not a function
        at /workspace/node_modules/@siemens/ix/components/src/components/modal/modal.tsx:212:19
        at Object.complete (/workspace/node_modules/@siemens/ix/components/src/components/modal/modal.tsx:140:11)
        at setCallback (/workspace/node_modules/@siemens/node_modules/animejs/lib/anime.es.js:1024:50)
        at setInstanceProgress (/workspace/node_modules/@siemens/node_modules/animejs/lib/anime.es.js:1080:11)
        at Object.instance.tick (/workspace/node_modules/@siemens/node_modules/animejs/lib/anime.es.js:1131:5)
        at step (/workspace/node_modules/@siemens/node_modules/animejs/lib/anime.es.js:879:24)
        at runAnimationFrameCallbacks (/workspace/node_modules/jsdom/lib/jsdom/browser/Window.js:599:13)
        at Timeout.<anonymous> (/workspace/node_modules/jsdom/lib/jsdom/browser/Window.js:577:11)
        at listOnTimeout (node:internal/timers:573:17)
        at processTimers (node:internal/timers:514:7)

      at VirtualConsole.<anonymous> (node_modules/jsdom/lib/jsdom/virtual-console.js:29:45)
      at reportException (node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:70:28)
      at runAnimationFrameCallbacks (node_modules/jsdom/lib/jsdom/browser/Window.js:601:13)
      at Timeout.<anonymous> (node_modules/jsdom/lib/jsdom/browser/Window.js:577:11)
```

### What type of frontend frameware are you seeing the problem on?

React

### Which version of iX do you use?

v2.1.0

### Code to produce this issue.

```shell
https://codesandbox.io/p/devbox/modaltest-pzzncm
```

**Comment by matthiashader** [comment]
Thanks for your insights! We will have a look into it, in an upcoming sprint 
Internal Ref [IX-982]

**Comment by cerenbattal** [comment]
Hi @matthiashader, 
what is the status of this issue? We are still facing the same problem with our unit tests with Jest. 

"react": "^18.2.0",
"@siemens/ix-react": "^2.5.0",
"jest": "^29.2.1",
"jest-environment-jsdom": "^29.3.1",
"@testing-library/jest-dom": "^5.16.5",
"@testing-library/react": "^13.4.0",
"@testing-library/user-event": "^12.8.3",

Thanks in advance.

**Comment by matthiashader** [comment]
Hello @cerenbattal.
After investigating the issue, it appears that jsdom doesn't currently support HTMLDialogElement, which is causing the tests to fail (you can find more details here): https://github.com/jsdom/jsdom/issues/3294.
As an alternative solution, you can mock the HTMLDialogElement methods using Jest or consider using happy-dom. I've prepared a small example for you here: herehttps://github.com/matthiashader/jest-happy-dom-example.
I hope this helps a little bit, if you have any more questions or need further assistance, feel free to ask!
