### ISSUE TITLE
Unhandled expection in ix-tooltip

### ISSUE THREAD

**Issue by TDaniel-evo** [siemens/ix#1329]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

I did not confirmed this but my best guess is that when an ix-tooltip's anchor element can not be found then the error is not handled.

Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'forEach')
TypeError: Cannot read properties of undefined (reading 'forEach')
    **at ix-tooltip.entry.js:203:28**
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (asyncToGenerator.js:3:24)
    at _next (asyncToGenerator.js:22:9)
    at _ZoneDelegate.invoke (zone.js:368:26)
    at Object.onInvoke (core.mjs:26259:33)
    at _ZoneDelegate.invoke (zone.js:367:52)
    at Zone.run (zone.js:129:43)
    at zone.js:1257:36
    at _ZoneDelegate.invokeTask (zone.js:402:31)
    at resolvePromise (zone.js:1193:31)
    at zone.js:1100:17
    at zone.js:1116:33
    at asyncGeneratorStep (asyncToGenerator.js:6:5)
    at _next (asyncToGenerator.js:22:9)
    at _ZoneDelegate.invoke (zone.js:368:26)
    at Object.onInvoke (core.mjs:26259:33)
    at _ZoneDelegate.invoke (zone.js:367:52)
    at Zone.run (zone.js:129:43)
    at zone.js:1257:36

### What type of frontend framework are you seeing the problem on?

Angular

### Which version of iX do you use?

v2.2.1

### Code to produce this issue.

```shell
<ix-tooltip for=".not-existing-element-or-not-valid-selector">Text</ix-tooltip>
```

**Comment by danielleroux** [comment]
This is already addressed by https://github.com/siemens/ix/pull/1251. Will will close this one here.
