### ISSUE TITLE
Chart rendering issue with siemens/ix-echarts ^2.3.0 (Renderer 'undefined' is not imported. Please import it first.)

### ISSUE THREAD

**Issue by sakethsusarla** [siemens/ix#1505]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

**Description:**

### Expected Behavior
When using `siemens/ix-echarts` version ^2.3.0, charts should render correctly as it does with version ^1.6.0.

### Actual Behavior
After upgrading to `siemens/ix-echarts` version ^2.3.0, charts fail to render and the following error appears in the console:
```
ERROR Error: Uncaught (in promise): Error: Renderer 'undefined' is not imported. Please import it first.
Error: Renderer 'undefined' is not imported. Please import it first.
    at new ZRender (vendor.js:116727:15)
    at Module.init (vendor.js:116955:12)
    at new ECharts (vendor.js:78008:78)
    at init (vendor.js:79761:15)
    at vendor.js:117222:13
    at _ZoneDelegate.invoke (polyfills.js:7543:158)
    at Zone.run (polyfills.js:7326:35)
    at polyfills.js:8418:28
    at _ZoneDelegate.invokeTask (polyfills.js:7570:171)
    at Zone.runTask (polyfills.js:7372:37)
    at new ZRender (vendor.js:116727:15)
    at Module.init (vendor.js:116955:12)
    at new ECharts (vendor.js:78008:78)
    at init (vendor.js:79761:15)
    at vendor.js:117222:13
    at _ZoneDelegate.invoke (polyfills.js:7543:158)
    at Zone.run (polyfills.js:7326:35)
    at polyfills.js:8418:28
    at _ZoneDelegate.invokeTask (polyfills.js:7570:171)
    at Zone.runTask (polyfills.js:7372:37)
    at resolvePromise (polyfills.js:8358:19)
    at polyfills.js:8268:9
    at polyfills.js:8283:25
    at asyncGeneratorStep (vendor.js:117538:5)
    at _throw (vendor.js:117557:9)
    at _ZoneDelegate.invoke (polyfills.js:7543:158)
    at Object.onInvoke (vendor.js:53313:25)
    at _ZoneDelegate.invoke (polyfills.js:7543:46)
    at Zone.run (polyfills.js:7326:35)
    at polyfills.js:8418:28
```

### Reproduction Steps
1. Clone the repository: [issue-echarts-renderer-siemens-ix-v2_3_0](https://github.com/sakethsusarla/issue-echarts-renderer-siemens-ix-v2_3_0)
2. Install dependencies: `npm install`
3. Run the application: `npm start`
4. Observe the console for the error and the line chart not rendering.

### Additional Context
- The issue does not occur with `siemens/ix-echarts` version ^1.6.0.
- The error suggests that a renderer is not imported, but it is unclear which renderer is required or how to import it.

Please let me know if any additional information is needed.

### What type of frontend framework are you seeing the problem on?

Angular

### Which version of iX do you use?

2.5.0

### Code to produce this issue.

```shell
https://github.com/sakethsusarla/issue-echarts-renderer-siemens-ix-v2_3_0
```

**Comment by matthiashader** [comment]
Hello @sakethsusarla! The problem is in your app.module.ts, according to the ngx-echarts documentation (https://github.com/xieziyu/ngx-echarts?tab=readme-ov-file#ngmodule), the NgxEchartsModule should be imported like:
` NgxEchartsModule.forRoot({ echarts: () => import('echarts'), }),`

**Comment by sakethsusarla** [comment]
Many thanks 😅, the issue got fixed with this change.
