### ISSUE TITLE
Error with basic auth in URL

### ISSUE THREAD

**Issue by lukaselmer** [siemens/ix#628]
### What happened?

If you have a url with basic auth in the URL (e.g. https://user:password@example.com), there is an error in the JS, so that execution stops and the JS/CSS is not injected/rendered. Error:

<img width="965" alt="image" src="https://github.com/siemens/ix/assets/326935/a36070a5-b49a-4003-83a1-c32bbf803f8c">

```
TypeError: Cannot read properties of undefined (reading '$instanceValues$')
    at wh (index-8dadc234.js:40:68626)
    at x.get [as selected] (index-8dadc234.js:40:69210)
    at x.render (ix-event-list_2.entry-1d99ca22.js:1:5672)
    at vh (index-8dadc234.js:40:67865)
    at mh (index-8dadc234.js:40:67694)
    at index-8dadc234.js:40:67494
    at Ou (index-8dadc234.js:40:67547)
    at yh (index-8dadc234.js:40:67485)
    at Array.<anonymous> (index-8dadc234.js:40:67197)
    at Iu (index-8dadc234.js:40:83099) <ix-event-list-item color=​"color-primary" class=​"hydrated">​…​</ix-event-list-item>​
x @ index-8dadc234.js:40
```

Rendered (wrong):

<img width="520" alt="image" src="https://github.com/siemens/ix/assets/326935/baaba32f-768f-4286-9a18-a87116f2adcf">

Rendered (how it should be / when you enter the credentials manually):

<img width="599" alt="image" src="https://github.com/siemens/ix/assets/326935/e80e5c78-2d20-4b4b-8dba-1aea6126ed3b">

You can find the full code here: https://code.siemens.com/tracks-ops/depot-config/-/tree/develop/infrastructure/iltis-rocks/protected.iltis.rocks

### What type of frontend frameware are you seeing the problem on?

React

### Which version of iX do you use?

1.6.0

### Code to produce this issue.

```shell
https://code.siemens.com/tracks-ops/depot-config/-/tree/develop/infrastructure/iltis-rocks/protected.iltis.rocks
```

**Comment by matthiashader** [comment]
Internal ref [IX-913]

**Comment by nuke-ellington** [comment]
Closing this since we got no response when reaching out directly. Also version 1.6.0 is no longer maintained.
